version: "3.8"

services:
  # ----------------------------------------------------------------------------
  # БД для Opencart
  mysql-1:
    image: mysql:5.7
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - doccomp

  # ----------------------------------------------------------------------------
  # Сам Opencart
  opencart:
    image: php:7.4-apache
    container_name: opencart-1
    depends_on:
      - mysql-1
    volumes:
      - ./opencart_code:/var/www/html:cached
    environment:
      # если позже понадобятся, можно в конфигурации config.php их взять
      DB_DRIVER: mysqli
      DB_HOSTNAME: mysql-1
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: opencart
      DB_PORT: 3306
    # убрал проброс 80→8080, чтобы не конфликтовать с Jenkins
    networks:
      - doccomp

  # ----------------------------------------------------------------------------
  # Администратор БД в браузере
  adminer-1:
    image: adminer:latest
    container_name: adminer-1
    restart: always
    ports:
      - "8082:8080"
    networks:
      - doccomp

  # ----------------------------------------------------------------------------
  # Selenoid
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    restart: always
    volumes:
      - ./config/browsers.json:/etc/selenoid/browsers.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4444:4444"
    networks:
      - doccomp

  # ----------------------------------------------------------------------------
  # Веб-GUI для Selenoid
  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    restart: always
    depends_on:
      - selenoid
    ports:
      - "8081:8080"
    networks:
      - doccomp

  # ----------------------------------------------------------------------------
  # Jenkins
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-jenkins:latest
    container_name: jenkins
    restart: always
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - doccomp

networks:
  doccomp:

volumes:
  jenkins_home:
