version: '3.9'

networks:
  selenoid_net:
    driver: bridge

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    networks:
      - selenoid_net
    ports:
      - "4444:4444"
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit", "5", "-timeout", "3m"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    networks:
      - selenoid_net
    ports:
      - "8081:8080"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-jenkins:latest
    container_name: jenkins
    networks:
      - selenoid_net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
